# -*- coding: utf-8 -*-
"""groq_film

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tcbH4a4AxUVtSoOTqqsjUGzOZ4vRaYpI
"""

!pip install langchain-groq

import os
import getpass

# Inisialisasi API Key Groq
if "GROQ_API_KEY" not in os.environ:
    os.environ["GROQ_API_KEY"] = getpass.getpass("GROQ_API_KEY ")

from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate

# Inisialisasi model Groq LLM
llm = ChatGroq(model="llama-3.1-8b-instant", temperature=0.8)

# Prompt utama
system_prompt = """
Kamu adalah Chatbot Film yang ramah, seru, dan selalu fokus hanya membicarakan seputar film
(rekomendasi, sinopsis, detail pemeran, genre, fakta menarik).
Kamu bukan hanya pemberi rekomendasi, tapi juga teman diskusi film yang bisa ngobrol panjang.

Aturan utama:
1. Selalu ingat konteks percakapan sebelumnya agar jawaban nyambung (misalnya, jika user bertanya film Indonesia setelah sebelumnya minta film lucu, maka jawab dengan film Indonesia lucu, bukan random lagi).
2. Jika user mengetik 'keluar', ucapkan selamat tinggal dengan gaya ramah dan kreatif, contohnya:
   "Terima kasih sudah ngobrol soal film bareng aku. Semoga filmnya seru ya! Sampai jumpa 👋"
3. Jangan keluar topik film. Jika user menanyakan hal di luar film, tolak dengan sopan dan ajak balik ke topik film.
4. Jika user minta rekomendasi film, berikan daftar minimal 2–3 film dengan detail: judul, tahun rilis, genre, sinopsis singkat, dan pemeran utama.
5. Jika user ingin diskusi, tanggapi dengan antusias dan bisa menambahkan fakta menarik tentang film, sutradara, atau aktor.

Fokus utama: jadi teman ngobrol seputar film dengan jawaban detail dan tetap nyambung dalam percakapan.
"""

# Prompt template
prompt = ChatPromptTemplate.from_messages([
    ("system", system_prompt),
    ("human", "{user_input}")
])

# Sambutan awal (This part will still print the welcome message once)
print("🎬 Selamat datang di Chatbot Film!")
print("Saya siap menemani obrolanmu seputar film. 🎥")
print("Ketik 'keluar' untuk mengakhiri percakapan.\n")

# Loop percakapan
while True:
    user_input = input("Anda: ")
    if user_input.lower() == "keluar":
        print("\n🍿 Terima kasih sudah ngobrol bareng Chatbot Film!")
        print("Semoga rekomendasi dan diskusinya bermanfaat. Sampai jumpa di layar berikutnya! 🎞️👋")
        break

    # Send user input to the LLM
    chain = prompt | llm
    response = chain.invoke({"user_input": user_input})
    print("mimin:", response.content, "\n")

# Loop percakapan
while True:
    user_input = input("Anda: ")
    if user_input.lower() == "keluar":
        print("\n🍿 Terima kasih sudah ngobrol bareng Chatbot Film!")
        print("Semoga rekomendasi dan diskusinya bermanfaat. Sampai jumpa di layar berikutnya! 🎞️👋")
        break

    # Send user input to the LLM
    chain = prompt | llm
    response = chain.invoke({"user_input": user_input})
    print("mimin:", response.content, "\n")